name: dailyquest2
description: A habit and agenda tracker powered by Supabase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Supabase integration
  supabase_flutter: ^2.9.0

  # Ambil gambar dari galeri/kamera
  image_picker: ^1.1.0

  fl_chart:
    ^0.64.0

    # Format tanggal
  intl: ^0.19.0

  # Notifikasi lokal (reminder tugas)
  flutter_local_notifications: ^14.1.1

  # State management (jika kamu pakai Provider)
  provider: ^6.1.2

  # Icon iOS
  cupertino_icons: ^1.0.2

  # Loading animation (opsional)
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/fonts/
